[package]
name = "binarysearch"
version = "0.1.0"
authors = ["Hoppy0616 <hodahoda.20430@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
